spring:
  application:
    name: UIClient
server:
  port: 8083
catalog:
  service:
    url: https://catalog-nttd.cfapps.io/api/v1/Catalogs
orders:
  service:
    url: https://orders-nttd.cfapps.io/orders    
connect:
  timeout: 10000
read: 
  timeout: 10000
